# Generated by Django 2.2.3 on 2019-07-28 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=16, null=True, verbose_name='Dosya Adı')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', verbose_name='Dokumanlarım')),
            ],
        ),
        migrations.CreateModel(
            name='UserDefinedCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Code')),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='user_defined_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.UserDefinedCode'),
        ),
    ]
