# Generated by Django 2.2.3 on 2019-07-23 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190723_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='fallow',
            field=models.ManyToManyField(related_name='_usertable_fallow_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
