# Generated by Django 2.2.3 on 2019-07-25 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_dokuman', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DocumentsOwner',
        ),
    ]
