# Generated by Django 2.2.3 on 2019-07-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20190724_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='hash',
            new_name='file_hash',
        ),
    ]
