# Generated by Django 2.2.3 on 2019-07-23 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20190723_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='type',
        ),
        migrations.AddField(
            model_name='documents',
            name='type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.my_codes', verbose_name='Dosta Türü'),
        ),
    ]
