# Generated by Django 2.2.3 on 2019-07-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20190724_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=21)),
                ('file', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/%d', verbose_name='Dokumanlarım'),
        ),
    ]
