# Generated by Django 2.2.3 on 2019-07-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20190725_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='user_id',
            new_name='user',
        ),
    ]
