# Generated by Django 2.2.3 on 2019-07-23 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_auto_20190723_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='comment',
            field=models.TextField(default=256),
        ),
        migrations.CreateModel(
            name='favori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=5, null=True)),
                ('doc_id', models.ForeignKey(blank=True, null=True, on_delete=True, to='documents.Documents')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
