# Generated by Django 2.2.3 on 2019-07-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20190724_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='zfile',
            name='image_sha1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
