# Generated by Django 2.2.3 on 2019-07-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_zfile_image_sha1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='type_id',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='zfile',
            name='title',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
