# Generated by Django 2.2.3 on 2019-07-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20190723_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='fallow',
            field=models.ManyToManyField(related_name='_documents_fallow_+', to='documents.Documents'),
        ),
        migrations.DeleteModel(
            name='favori',
        ),
    ]
