# Generated by Django 2.2.3 on 2019-07-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20190724_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='file_hash',
            new_name='file_sha1',
        ),
    ]
