# Generated by Django 2.2.3 on 2019-07-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20190724_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
        migrations.DeleteModel(
            name='zfile',
        ),
        migrations.RenameField(
            model_name='documents',
            old_name='title',
            new_name='label',
        ),
    ]
